"""
Django settings for angola_api project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import json
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.forms import ValidationError


# Ensuite utiliser


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


with open(BASE_DIR.joinpath('angola_api/proprieties.json')) as f:
    SECRETS = json.load(f)
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRETS['KEY']

ADMIN_URL = 'django-admin/'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL= 'operation.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'channels',
    'operation'
]

# Configuration Channels
ASGI_APPLICATION = 'angola_api.asgi.application'

# Channel Layers - PRODUCTION avec Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
            "capacity": 1500,
            "expiry": 10,
        },
    },
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'operation.middleware.JWTDebugMiddleware', 
]

ROOT_URLCONF = 'angola_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'file_charset': 'utf-8',
        },
    },
]

WSGI_APPLICATION = 'angola_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Configuration de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # ✅ OBLIGATOIRE
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'UNICODE_JSON': True,
    'COMPACT_JSON': True,
}

# Configuration de Simple JWT
from datetime import timedelta

SIMPLE_JWT = {
    # 🧪 CONFIGURATION TEST - TOKENS TRÈS LONGS
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),     # 1 an au lieu de 1 jour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=730),    # 2 ans au lieu de 7 jours
    
    # OU POUR VRAIMENT TESTER - TOKENS "INFINIS"
    # 'ACCESS_TOKEN_LIFETIME': timedelta(days=36500),  # 100 ans = quasi infini
    # 'REFRESH_TOKEN_LIFETIME': timedelta(days=36500), # 100 ans = quasi infini
    
    'ROTATE_REFRESH_TOKENS': False,                   # Désactiver rotation pour test
    'BLACKLIST_AFTER_ROTATION': False,               # Pas de blacklist pour test
    'UPDATE_LAST_LOGIN': False,
    
    # Configuration standard
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    
    # 🧪 DÉSACTIVER VÉRIFICATIONS STRICTES POUR TEST
    'VERIFY_SIGNATURE': True,     # Garder la vérification signature
    'VERIFY_EXP': True,          # Mais avec expiration très lointaine
    'REQUIRE_EXP': True,
    'LEEWAY': timedelta(minutes=5),  # Tolérance de 5 minutes
}

# Configuration CORS
CORS_ALLOW_ALL_ORIGINS = True  # Pour le développement uniquement, limitez en production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    # 'HEAD',  # Ajouté pour Flutter
]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
#     'cache-control',
#     'pragma',
#     'expires',
#     'if-modified-since',
#     'content-disposition',
#     # Headers spécifiques pour mobile/Flutter
#     'x-forwarded-for',
#     'x-forwarded-proto',
#     'x-real-ip',
# ]

# CORS_EXPOSE_HEADERS = [
#     'content-type',
#     'content-length',
#     'content-disposition',
#     'cache-control',
#     'expires',
#     'pragma',
# ]


CORS_PREFLIGHT_MAX_AGE = 86400  
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Configuration du modèle utilisateur personnalisé
# AUTH_USER_MODEL = 'api.User'

# Configuration des médias
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'


DATABASES = {
    'default': {

        'ENGINE': 'django.db.backends.postgresql',
        'NAME': SECRETS['NAME'],
        'USER': SECRETS['USER'],
        'PASSWORD': SECRETS['PASS'] ,
        'HOST': SECRETS['HOST'], 
        'PORT':  SECRETS['PORT'],
        'OPTIONS': {
            'client_encoding': 'UTF8',
            
        },
    }
    # {
    #     "KEY": "django-insecure--jl61o0a8m3!+$+d$d2ql0^twj2e@0l^0e*)w4q(_b=@4517_z",
    #     "NAME": "angola_api",
    #     "USER": "postgres",
    #     "HOST": "localhost",
    #     "PORT": "5432",
    #     "PASS": "#!@dm1n!#"
    # }
    
    # {
    #     "KEY": "django-insecure--jl61o0a8m3!+$+d$d2ql0^twj2e@0l^0e*)w4q(_b=@4517_z",
    #     "NAME": "angola_db",
    #     "USER": "angola_user",
    #     "HOST": "dpg-d0rpn2s9c44c73cfdvmg-a.oregon-postgres.render.com",
    #     "PORT": "5432",
    #     "PASS": "T4QjF2WRVBABrweDn1ROtG36ZEY9Xryn"
    # }

    # {
    #     "KEY": "django-insecure--jl61o0a8m3!+$+d$d2ql0^twj2e@0l^0e*)w4q(_b=@4517_z",
    #     "NAME": "angola_db_fzta",
    #     "USER": "angola_db_user",
    #     "HOST": "dpg-d1gjocmmcj7s73csa70g-a.oregon-postgres.render.com",
    #     "PORT": "5432",
    #     "PASS": "4qwsXj8nrYPbWCpT9sFnT3M14WcLTwpy"
    # }

    # {
    #     "KEY": "django-insecure--jl61o0a8m3!+$+d$d2ql0^twj2e@0l^0e*)w4q(_b=@4517_z",
    #     "NAME": "angola_db",
    #     "USER": "angola_db_user",
    #     "HOST": "localhost",
    #     "PORT": "5432",
    #     "PASS": "4qwsXj8nrYPbWCpT9sFnT3M14WcLTwpy"
    # }
}


# Configuration pour l'envoi d'emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Remplacez par votre serveur SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'spinnaldev@gmail.com'
EMAIL_HOST_PASSWORD = 'zvzi foix bgnb juxn' 
DEFAULT_FROM_EMAIL = 'TEYAGO APP <spinnaldev@gmail.com>'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Langues supportées
LANGUAGES = [
    ('fr', _('Français')),
    ('en', _('English')),
    ('pt', _('Português')),
]

# Répertoires des fichiers de traduction
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


# Taille maximale des fichiers uploadés
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10MB

# Types de fichiers autorisés pour les images de profil
ALLOWED_IMAGE_TYPES = [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
]


# Fonction utilitaire pour valider les images
def validate_image(image):
    """
    Valider qu'un fichier uploadé est une image valide
    """
    if image.content_type not in ALLOWED_IMAGE_TYPES:
        raise ValidationError('Type de fichier non autorisé')
    
    if image.size > 5 * 1024 * 1024:  # 5MB max
        raise ValidationError('Fichier trop volumineux (max 5MB)')
    
    return image

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# Configuration des logs

# Configuration des logs
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'operation': {  # Changé de 'myapp' à 'operation' selon votre app
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_CHARSET = 'utf-8'


# {
#     "KEY": "django-insecure--jl61o0a8m3!+$+d$d2ql0^twj2e@0l^0e*)w4q(_b=@4517_z",
#     "NAME": "angola_db_fzta",
#     "USER": "angola_db_user",
#     "HOST": "dpg-d1gjocmmcj7s73csa70g-a.oregon-postgres.render.com",
#     "PORT": "5432",
#     "PASS": "4qwsXj8nrYPbWCpT9sFnT3M14WcLTwpy"
# }