# Generated by Django 5.2 on 2025-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_resetpasswordcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image de catégorie"),
        ),
    ]
