# Generated by Django 5.2 on 2025-04-30 08:18

from django.db import migrations
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_category_image_url'),
    ]
    
    def create_categories_and_subcategories(apps, schema_editor):
        CATEGORIES = [
            {
                'id': 1,
                'name': 'Maison & Construction',
                'description': 'Services pour la construction, rénovation et entretien de la maison',
                'icon': 'home',
                'image_url': 'https://images.unsplash.com/photo-1593604572574-ab4f4b3c7dd6?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 1,
                        'name': 'Construction & Rénovation',
                        'description': 'Maçons, architectes, entreprises de construction',
                        'icon': 'construction'
                    },
                    {
                        'id': 2,
                        'name': 'Plomberie',
                        'description': 'Installation et réparation de plomberie',
                        'icon': 'water'
                    },
                    {
                        'id': 3,
                        'name': 'Électricité',
                        'description': 'Installation de câblage, réparation électrique',
                        'icon': 'flash_on'
                    },
                    {
                        'id': 4,
                        'name': 'Menuiserie & Ébénisterie',
                        'description': 'Fabrication et réparation de meubles',
                        'icon': 'carpenter'
                    },
                    {
                        'id': 5,
                        'name': 'Peinture & Décoration',
                        'description': 'Peintres en bâtiment, décorateurs d\'intérieur',
                        'icon': 'format_paint'
                    },
                    {
                        'id': 6,
                        'name': 'Paysagisme & Jardinage',
                        'description': 'Conception et entretien d\'espaces verts',
                        'icon': 'yard'
                    },
                    {
                        'id': 7,
                        'name': 'Serrurerie',
                        'description': 'Installation et dépannage de serrures',
                        'icon': 'lock'
                    },
                    {
                        'id': 8,
                        'name': 'Ménage & Nettoyage',
                        'description': 'Nettoyage à domicile, entretien de bureaux',
                        'icon': 'cleaning_services'
                    },
                    {
                        'id': 9,
                        'name': 'Pest Control',
                        'description': 'Désinsectisation, dératisation',
                        'icon': 'bug_report'
                    },
                    {
                        'id': 10,
                        'name': 'Vitrerie & Fenêtres',
                        'description': 'Réparation et pose de vitres, stores, rideaux',
                        'icon': 'window'
                    },
                    {
                        'id': 11,
                        'name': 'Froid & Climatisation',
                        'description': 'Installation et réparation de climatiseurs et réfrigérateurs',
                        'icon': 'ac_unit'
                    }
                ]
            },
            {
                'id': 2,
                'name': 'Bien-être & Beauté',
                'description': 'Services de soins personnels et de beauté',
                'icon': 'spa',
                'image_url': 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 12,
                        'name': 'Coiffure & Barbier',
                        'description': 'Coiffeurs à domicile, salons de beauté',
                        'icon': 'content_cut'
                    },
                    {
                        'id': 13,
                        'name': 'Esthétique & Maquillage',
                        'description': 'Manucure, soins du visage, maquilleurs professionnels',
                        'icon': 'face'
                    },
                    {
                        'id': 14,
                        'name': 'Massages & Thérapies',
                        'description': 'Massothérapeutes, spa, réflexologie',
                        'icon': 'spa'
                    },
                    {
                        'id': 15,
                        'name': 'Fitness & Coaching Sportif',
                        'description': 'Coachs personnels, entraîneurs de gym, yoga',
                        'icon': 'fitness_center'
                    },
                    {
                        'id': 16,
                        'name': 'Nutrition & Diététique',
                        'description': 'Consultants en alimentation saine',
                        'icon': 'restaurant_menu'
                    }
                ]
            },
            {
                'id': 3,
                'name': 'Événements & Artistiques',
                'description': 'Services pour l\'organisation d\'événements et prestations artistiques',
                'icon': 'event',
                'image_url': 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 17,
                        'name': 'Photographie & Vidéographie',
                        'description': 'Mariages, événements, shootings professionnels',
                        'icon': 'camera_alt'
                    },
                    {
                        'id': 18,
                        'name': 'Organisation d\'événements',
                        'description': 'Wedding planners, corporate events',
                        'icon': 'event_available'
                    },
                    {
                        'id': 19,
                        'name': 'Traiteur & Chef à domicile',
                        'description': 'Services de restauration, chefs personnels',
                        'icon': 'restaurant'
                    },
                    {
                        'id': 20,
                        'name': 'Animation & Spectacle',
                        'description': 'DJ, musiciens, humoristes',
                        'icon': 'music_note'
                    },
                    {
                        'id': 21,
                        'name': 'Location de matériel',
                        'description': 'Tentes, chaises, équipements audio',
                        'icon': 'chair'
                    },
                    {
                        'id': 22,
                        'name': 'Fleuristes & Décoration florale',
                        'description': 'Mariages, funérailles, anniversaires',
                        'icon': 'local_florist'
                    }
                ]
            },
            {
                'id': 4,
                'name': 'Transport & Logistique',
                'description': 'Services de transport de personnes et marchandises',
                'icon': 'local_shipping',
                'image_url': 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 23,
                        'name': 'Chauffeurs & VTC',
                        'description': 'Uber, Bolt, chauffeurs privés',
                        'icon': 'directions_car'
                    },
                    {
                        'id': 24,
                        'name': 'Déménagement & Livraison',
                        'description': 'Transport de meubles, marchandises, courses à domicile',
                        'icon': 'move_to_inbox'
                    },
                    {
                        'id': 25,
                        'name': 'Mécaniciens & Réparateurs automobiles',
                        'description': 'Réparation, dépannage, maintenance',
                        'icon': 'build'
                    },
                    {
                        'id': 26,
                        'name': 'Lavage Auto',
                        'description': 'Services à domicile ou en station',
                        'icon': 'local_car_wash'
                    }
                ]
            },
            {
                'id': 5,
                'name': 'Santé & Bien-être',
                'description': 'Services liés à la santé et au bien-être',
                'icon': 'favorite',
                'image_url': 'https://images.unsplash.com/photo-1579684288361-5c1a2957cc38?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 27,
                        'name': 'Infirmiers & Soins à domicile',
                        'description': 'Soins aux personnes âgées, perfusions',
                        'icon': 'health_and_safety'
                    },
                    {
                        'id': 28,
                        'name': 'Psychologues & Thérapeutes',
                        'description': 'Consultations privées, gestion du stress',
                        'icon': 'psychology'
                    },
                    {
                        'id': 29,
                        'name': 'Orthophonistes & Kinésithérapeutes',
                        'description': 'Rééducation, thérapie du langage',
                        'icon': 'accessibility'
                    }
                ]
            },
            {
                'id': 6,
                'name': 'Services Professionnels & Formation',
                'description': 'Services professionnels et formations diverses',
                'icon': 'work',
                'image_url': 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 30,
                        'name': 'Avocats & Conseillers juridiques',
                        'description': 'Droits des affaires, immobilier, divorce',
                        'icon': 'gavel'
                    },
                    {
                        'id': 31,
                        'name': 'Comptables & Fiscalistes',
                        'description': 'Gestion d\'impôts, comptabilité d\'entreprise',
                        'icon': 'calculate'
                    },
                    {
                        'id': 32,
                        'name': 'Consultants & Coachs de carrière',
                        'description': 'Business consulting, développement personnel',
                        'icon': 'person'
                    },
                    {
                        'id': 33,
                        'name': 'Traduction & Interprétation',
                        'description': 'Portugais-français-anglais, etc.',
                        'icon': 'translate'
                    },
                    {
                        'id': 34,
                        'name': 'Formations & Cours particuliers',
                        'description': 'Langues, informatique, musique, soutien scolaire',
                        'icon': 'school'
                    }
                ]
            },
            {
                'id': 7,
                'name': 'Services Numériques & Technologiques',
                'description': 'Services liés au numérique et aux technologies',
                'icon': 'computer',
                'image_url': 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 35,
                        'name': 'Développement Web & Mobile',
                        'description': 'Création de sites, applications',
                        'icon': 'code'
                    },
                    {
                        'id': 36,
                        'name': 'Graphisme & Design',
                        'description': 'Logos, flyers, design UX/UI',
                        'icon': 'brush'
                    },
                    {
                        'id': 37,
                        'name': 'Marketing Digital & Réseaux sociaux',
                        'description': 'Community management, publicité en ligne',
                        'icon': 'trending_up'
                    },
                    {
                        'id': 38,
                        'name': 'Support Informatique & Réparation',
                        'description': 'Dépannage PC, installation de logiciels',
                        'icon': 'build_circle'
                    }
                ]
            },
            {
                'id': 8,
                'name': 'Services pour Animaux',
                'description': 'Services de soins et garde d\'animaux',
                'icon': 'pets',
                'image_url': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 39,
                        'name': 'Vétérinaires & Soins pour animaux',
                        'description': 'Vaccins, consultations',
                        'icon': 'medical_services'
                    },
                    {
                        'id': 40,
                        'name': 'Toilettage pour animaux',
                        'description': 'Bains, coupes, soins spécialisés',
                        'icon': 'shower'
                    },
                    {
                        'id': 41,
                        'name': 'Dresseurs & Garde d\'animaux',
                        'description': 'Dog-sitting, dressage',
                        'icon': 'pets'
                    }
                ]
            },
            {
                'id': 9,
                'name': 'Services Divers',
                'description': 'Autres services spécialisés',
                'icon': 'miscellaneous_services',
                'image_url': 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3',
                'subcategories': [
                    {
                        'id': 42,
                        'name': 'Agents de sécurité & Gardiennage',
                        'description': 'Sécurité privée, surveillance',
                        'icon': 'security'
                    },
                    {
                        'id': 43,
                        'name': 'Conciergerie & Services à domicile',
                        'description': 'Courses, gestion de propriétés',
                        'icon': 'room_service'
                    },
                    {
                        'id': 44,
                        'name': 'Fabrication & Vente sur mesure',
                        'description': 'Couturiers, tailleurs, cordonniers',
                        'icon': 'shopping_basket'
                    }
                ]
            }
        ]
        # Obtenir les modèles
        Category = apps.get_model('operation', 'Category')
        SubCategory = apps.get_model('operation', 'SubCategory')
        
        # Créer les catégories et sous-catégories
        for category_data in CATEGORIES:
            subcategories_data = category_data.pop('subcategories')
            
            # Créer la catégorie
            category = Category.objects.create(
                id=category_data['id'],
                name=category_data['name'],
                description=category_data['description'],
                icon=category_data['icon'],
                created_at=timezone.now(),
                updated_at=timezone.now()
            )
            
            # Créer les sous-catégories associées
            for subcategory_data in subcategories_data:
                SubCategory.objects.create(
                    id=subcategory_data['id'],
                    name=subcategory_data['name'],
                    description=subcategory_data['description'],
                    icon=subcategory_data['icon'],
                    category=category,
                    created_at=timezone.now(),
                    updated_at=timezone.now()
                )

    def delete_categories_and_subcategories(apps, schema_editor):
        # Obtenir les modèles
        Category = apps.get_model('operation', 'Category')
        SubCategory = apps.get_model('operation', 'SubCategory')
        
        # Supprimer toutes les catégories et sous-catégories
        SubCategory.objects.all().delete()
        Category.objects.all().delete()

    operations = [
        migrations.RunPython(create_categories_and_subcategories, delete_categories_and_subcategories),
    ]
