# Generated by Django 5.2 on 2025-05-02 15:21

from django.db import migrations
from operation.models import Category

class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20250430_0918'),
    ]
    def update_categories(apps, schema_editor):
        CATEGORIES_DATA = [
            {
                'id': 1,
                'name': 'Maison & Construction',
                'image_url': 'https://images.unsplash.com/photo-1593604572574-ab4f4b3c7dd6?ixlib=rb-4.0.3'
            },
            {
                'id': 2,
                'name': 'Bien-être & Beauté',
                'image_url': 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?ixlib=rb-4.0.3'
            },
            {
                'id': 3,
                'name': 'Événements & Artistiques',
                'image_url': 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-4.0.3'
            },
            {
                'id': 4,
                'name': 'Transport & Logistique',
                'image_url': 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?ixlib=rb-4.0.3'
            },
            {
                'id': 5,
                'name': 'Santé & Bien-être',
                'image_url': 'https://images.unsplash.com/photo-1579684288361-5c1a2957cc38?ixlib=rb-4.0.3'
            },
            {
                'id': 6,
                'name': 'Services Professionnels & Formation',
                'image_url': 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3'
            },
            {
                'id': 7,
                'name': 'Services Numériques & Technologiques',
                'image_url': 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3'
            },
            {
                'id': 8,
                'name': 'Services pour Animaux',
                'image_url': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?ixlib=rb-4.0.3'
            },
            {
                'id': 9,
                'name': 'Services Divers',
                'image_url': 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3'
            }
        ]
        success_count = 0
        for cat_data in CATEGORIES_DATA:
            try:
                # Récupérer la catégorie existante par ID
                category = Category.objects.get(id=cat_data['id'])
                
                # Mettre à jour l'URL de l'image
                category.image_url = cat_data['image_url']
                category.save()
                
                success_count += 1
                print(f"Catégorie {cat_data['id']} ({category.name}) mise à jour avec succès")
            except Category.DoesNotExist:
                print(f"Erreur: Catégorie ID {cat_data['id']} n'existe pas")
            except Exception as e:
                print(f"Erreur lors de la mise à jour de la catégorie {cat_data['id']}: {str(e)}")
    
    
    
    operations = [
        migrations.RunPython(update_categories)
    ]
