# Generated by Django 5.2 on 2025-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='expertise_categories',
            field=models.ManyToManyField(related_name='providers_with_expertise', to='operation.category'),
        ),
    ]
