# Generated by Django 5.2 on 2025-05-28 11:32

from django.db import migrations
# Generated by Django 5.2 on 2025-05-28 12:00

from django.db import migrations
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_servicegalleryimage_serviceoption'),
    ]
    
    def add_location_venues_category(apps, schema_editor):
        # Obtenir les modèles
        Category = apps.get_model('operation', 'Category')
        SubCategory = apps.get_model('operation', 'SubCategory')
        
        # Données de la nouvelle catégorie
        LOCATION_CATEGORY = {
            'id': 10,  # Assurez-vous que cet ID n'existe pas déjà
            'name': 'Location de lieux',
            'description': 'Location d\'espaces pour mariages, anniversaires et événements privés',
            'icon': 'location_on',
            'image_url': 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3',
            'subcategories': [
                {
                    'id': 45,  # Continuez la numérotation après la dernière sous-catégorie existante
                    'name': 'Salles de mariage',
                    'description': 'Espaces dédiés aux cérémonies et réceptions de mariage',
                    'icon': 'celebration'
                },
                {
                    'id': 46,
                    'name': 'Salles de réception',
                    'description': 'Salles polyvalentes pour anniversaires, baptêmes, communions',
                    'icon': 'party_mode'
                },
                {
                    'id': 47,
                    'name': 'Espaces événementiels',
                    'description': 'Lieux pour événements corporate, séminaires, conférences',
                    'icon': 'business_center'
                },
                {
                    'id': 48,
                    'name': 'Jardins & Terrasses',
                    'description': 'Espaces extérieurs avec jardins pour événements en plein air',
                    'icon': 'park'
                },
                {
                    'id': 49,
                    'name': 'Villas & Résidences privées',
                    'description': 'Location de villas complètes pour événements intimes',
                    'icon': 'house'
                },
                {
                    'id': 50,
                    'name': 'Salles communautaires',
                    'description': 'Centres communautaires, salles paroissiales',
                    'icon': 'people'
                },
                {
                    'id': 51,
                    'name': 'Espaces thématiques',
                    'description': 'Lieux avec décoration spécifique (beach club, rooftop, etc.)',
                    'icon': 'palette'
                }
            ]
        }
        
        # Extraire les données des sous-catégories
        subcategories_data = LOCATION_CATEGORY.pop('subcategories')
        
        # Créer la catégorie
        category = Category.objects.create(
            id=LOCATION_CATEGORY['id'],
            name=LOCATION_CATEGORY['name'],
            description=LOCATION_CATEGORY['description'],
            icon=LOCATION_CATEGORY['icon'],
            image_url=LOCATION_CATEGORY['image_url'],
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        
        # Créer les sous-catégories associées
        for subcategory_data in subcategories_data:
            SubCategory.objects.create(
                id=subcategory_data['id'],
                name=subcategory_data['name'],
                description=subcategory_data['description'],
                icon=subcategory_data['icon'],
                category=category,
                created_at=timezone.now(),
                updated_at=timezone.now()
            )

    def remove_location_venues_category(apps, schema_editor):
        # Obtenir les modèles
        Category = apps.get_model('operation', 'Category')
        SubCategory = apps.get_model('operation', 'SubCategory')
        
        # Supprimer la catégorie et ses sous-catégories (cascade automatique)
        try:
            category = Category.objects.get(id=10)
        except Category.DoesNotExist:
            pass

    operations = [
        # migrations.RunPython(add_location_venues_category, remove_location_venues_category),
    ]
