# Generated by Django 5.2 on 2025-06-16 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20250528_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('budget_range', models.CharField(choices=[('moins_500', 'Moins de 500 €'), ('500_1000', '500 à 1000 €'), ('1000_10000', '1000 à 10 000 €'), ('10000_plus', '10 000 € et plus'), ('sur_devis', 'Demande de devis')], max_length=20)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=255, verbose_name="Lieu d'intervention")),
                ('remote_possible', models.BooleanField(default=False, verbose_name='Télétravail possible')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite souhaitée')),
                ('urgency', models.CharField(choices=[('low', 'Pas urgent'), ('medium', 'Modérément urgent'), ('high', 'Urgent'), ('very_high', 'Très urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='open', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('contact_via_platform', models.BooleanField(default=True, verbose_name='Contact via la plateforme')),
                ('show_email', models.BooleanField(default=False, verbose_name="Afficher l'email")),
                ('show_phone', models.BooleanField(default=False, verbose_name='Afficher le téléphone')),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='operation.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to='operation.subcategory')),
            ],
            options={
                'verbose_name': 'Projet Client',
                'verbose_name_plural': 'Projets Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('is_required', models.BooleanField(default=True, verbose_name='Compétence obligatoire')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='operation.clientproject')),
            ],
            options={
                'verbose_name': 'Compétence Projet',
                'verbose_name_plural': 'Compétences Projets',
            },
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='operation.clientproject')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to='operation.provider')),
            ],
            options={
                'verbose_name': 'Projet Favori',
                'verbose_name_plural': 'Projets Favoris',
                'unique_together': {('project', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProjectOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix proposé')),
                ('delivery_time', models.PositiveIntegerField(verbose_name='Délai de livraison (en jours)')),
                ('message', models.TextField(verbose_name="Message d'accompagnement")),
                ('includes_materials', models.BooleanField(default=False, verbose_name='Matériaux inclus')),
                ('warranty_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Période de garantie (mois)')),
                ('travel_costs_included', models.BooleanField(default=True, verbose_name='Frais de déplacement inclus')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('viewed_by_client', models.BooleanField(default=False)),
                ('client_notes', models.TextField(blank=True, verbose_name='Notes du client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_offers', to='operation.clientproject')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_offers', to='operation.provider')),
            ],
            options={
                'verbose_name': 'Offre de Prestataire',
                'verbose_name_plural': 'Offres de Prestataires',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_views', to='operation.clientproject')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue Projet',
                'verbose_name_plural': 'Vues Projets',
                'unique_together': {('project', 'viewer', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='ProviderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience")),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='operation.provider')),
            ],
            options={
                'verbose_name': 'Compétence Prestataire',
                'verbose_name_plural': 'Compétences Prestataires',
                'unique_together': {('provider', 'name')},
            },
        ),
    ]
