# Generated by Django 5.2 on 2025-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_clientproject_projectskill_projectfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de completion'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='budget_range',
            field=models.CharField(choices=[('sur_devis', 'Sur devis'), ('0_500', 'Moins de 500AOA'), ('500_1000', '500AOA - 1000AOA'), ('1000_5000', '1000AOA - 5000AOA'), ('5000_15000', '5000AOA - 15000AOA'), ('15000_plus', 'Plus de 15000AOA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('closed', 'Clôturé'), ('paused', 'En pause'), ('cancelled', 'Annulé')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
