# Generated by Django 5.2 on 2025-07-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_clientproject_closed_at_clientproject_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='budget_range',
            field=models.CharField(choices=[('moins_500', 'Moins de 500 AOA'), ('500_1000', '500 à 1000 AOA'), ('1000_10000', '1000 à 10 000 AOA'), ('10000_plus', '10 000 AOA et plus'), ('sur_devis', 'Demande de devis')], max_length=20),
        ),
    ]
