# Generated by Django 5.2 on 2025-07-12 06:21

from django.db import migrations

def populate_translation_fields(apps, schema_editor):
    """
    Remplir les champs de traduction avec les données en français et anglais
    """
    Category = apps.get_model('operation', 'Category')
    SubCategory = apps.get_model('operation', 'SubCategory')
    
    # Données de traduction pour les catégories
    categories_translations = {
        1: {
            'name_en': 'Home & Construction',
            'name_fr': 'Maison & Construction',
            'description_en': 'Services for construction, renovation and home maintenance',
            'description_fr': 'Services pour la construction, rénovation et entretien de la maison'
        },
        2: {
            'name_en': 'Wellness & Beauty',
            'name_fr': 'Bien-être & Beauté',
            'description_en': 'Personal care and beauty services',
            'description_fr': 'Services de soins personnels et de beauté'
        },
        3: {
            'name_en': 'Events & Artistic',
            'name_fr': 'Événements & Artistiques',
            'description_en': 'Services for event organization and artistic performances',
            'description_fr': 'Services pour l\'organisation d\'événements et prestations artistiques'
        },
        4: {
            'name_en': 'Venue Rental',
            'name_fr': 'Location de lieux',
            'description_en': 'Space rental for weddings, birthdays and private events',
            'description_fr': 'Location d\'espaces pour mariages, anniversaires et événements privés'
        },
        5: {
            'name_en': 'Transport & Logistics',
            'name_fr': 'Transport & Logistique',
            'description_en': 'People and goods transportation services',
            'description_fr': 'Services de transport de personnes et marchandises'
        },
        6: {
            'name_en': 'Health & Wellness',
            'name_fr': 'Santé & Bien-être',
            'description_en': 'Health and wellness related services',
            'description_fr': 'Services liés à la santé et au bien-être'
        },
        7: {
            'name_en': 'Professional Services & Training',
            'name_fr': 'Services Professionnels & Formation',
            'description_en': 'Professional services and various training',
            'description_fr': 'Services professionnels et formations diverses'
        },
        8: {
            'name_en': 'Digital & Technology Services',
            'name_fr': 'Services Numériques & Technologiques',
            'description_en': 'Services related to digital and technologies',
            'description_fr': 'Services liés au numérique et aux technologies'
        },
        9: {
            'name_en': 'Pet Services',
            'name_fr': 'Services pour Animaux',
            'description_en': 'Pet care and boarding services',
            'description_fr': 'Services de soins et garde d\'animaux'
        },
        10: {
            'name_en': 'Miscellaneous Services',
            'name_fr': 'Services Divers',
            'description_en': 'Other specialized services',
            'description_fr': 'Autres services spécialisés'
        }
    }
    
    # Données de traduction pour les sous-catégories
    subcategories_translations = {
        1: {'name_en': 'Construction & Renovation', 'name_fr': 'Construction & Rénovation', 'description_en': 'Masons, architects, construction companies', 'description_fr': 'Maçons, architectes, entreprises de construction'},
        2: {'name_en': 'Plumbing', 'name_fr': 'Plomberie', 'description_en': 'Plumbing installation and repair', 'description_fr': 'Installation et réparation de plomberie'},
        3: {'name_en': 'Electricity', 'name_fr': 'Électricité', 'description_en': 'Wiring installation, electrical repair', 'description_fr': 'Installation de câblage, réparation électrique'},
        4: {'name_en': 'Carpentry & Cabinetmaking', 'name_fr': 'Menuiserie & Ébénisterie', 'description_en': 'Furniture manufacturing and repair', 'description_fr': 'Fabrication et réparation de meubles'},
        5: {'name_en': 'Painting & Decoration', 'name_fr': 'Peinture & Décoration', 'description_en': 'Building painters, interior decorators', 'description_fr': 'Peintres en bâtiment, décorateurs d\'intérieur'},
        6: {'name_en': 'Landscaping & Gardening', 'name_fr': 'Paysagisme & Jardinage', 'description_en': 'Design and maintenance of green spaces', 'description_fr': 'Conception et entretien d\'espaces verts'},
        7: {'name_en': 'Locksmithing', 'name_fr': 'Serrurerie', 'description_en': 'Lock installation and repair', 'description_fr': 'Installation et dépannage de serrures'},
        8: {'name_en': 'Cleaning & Housekeeping', 'name_fr': 'Ménage & Nettoyage', 'description_en': 'Home cleaning, office maintenance', 'description_fr': 'Nettoyage à domicile, entretien de bureaux'},
        9: {'name_en': 'Pest Control', 'name_fr': 'Pest Control', 'description_en': 'Pest control, rodent control', 'description_fr': 'Désinsectisation, dératisation'},
        10: {'name_en': 'Glazing & Windows', 'name_fr': 'Vitrerie & Fenêtres', 'description_en': 'Glass repair and installation, blinds, curtains', 'description_fr': 'Réparation et pose de vitres, stores, rideaux'},
        11: {'name_en': 'Refrigeration & Air Conditioning', 'name_fr': 'Froid & Climatisation', 'description_en': 'Installation and repair of air conditioners and refrigerators', 'description_fr': 'Installation et réparation de climatiseurs et réfrigérateurs'},
        12: {'name_en': 'Hairdressing & Barber', 'name_fr': 'Coiffure & Barbier', 'description_en': 'Home hairdressers, beauty salons', 'description_fr': 'Coiffeurs à domicile, salons de beauté'},
        13: {'name_en': 'Aesthetics & Makeup', 'name_fr': 'Esthétique & Maquillage', 'description_en': 'Manicure, facial care, professional makeup artists', 'description_fr': 'Manucure, soins du visage, maquilleurs professionnels'},
        14: {'name_en': 'Massages & Therapies', 'name_fr': 'Massages & Thérapies', 'description_en': 'Massage therapists, spa, reflexology', 'description_fr': 'Massothérapeutes, spa, réflexologie'},
        15: {'name_en': 'Fitness & Sports Coaching', 'name_fr': 'Fitness & Coaching Sportif', 'description_en': 'Personal trainers, gym coaches, yoga', 'description_fr': 'Coachs personnels, entraîneurs de gym, yoga'},
        16: {'name_en': 'Nutrition & Dietetics', 'name_fr': 'Nutrition & Diététique', 'description_en': 'Healthy eating consultants', 'description_fr': 'Consultants en alimentation saine'},
        17: {'name_en': 'Photography & Videography', 'name_fr': 'Photographie & Vidéographie', 'description_en': 'Weddings, events, professional shoots', 'description_fr': 'Mariages, événements, shootings professionnels'},
        18: {'name_en': 'Event Organization', 'name_fr': 'Organisation d\'événements', 'description_en': 'Wedding planners, corporate events', 'description_fr': 'Wedding planners, corporate events'},
        19: {'name_en': 'Catering & Personal Chef', 'name_fr': 'Traiteur & Chef à domicile', 'description_en': 'Catering services, personal chefs', 'description_fr': 'Services de restauration, chefs personnels'},
        20: {'name_en': 'Entertainment & Shows', 'name_fr': 'Animation & Spectacle', 'description_en': 'DJs, musicians, comedians', 'description_fr': 'DJ, musiciens, humoristes'},
        21: {'name_en': 'Equipment Rental', 'name_fr': 'Location de matériel', 'description_en': 'Tents, chairs, audio equipment', 'description_fr': 'Tentes, chaises, équipements audio'},
        22: {'name_en': 'Florists & Floral Decoration', 'name_fr': 'Fleuristes & Décoration florale', 'description_en': 'Weddings, funerals, birthdays', 'description_fr': 'Mariages, funérailles, anniversaires'},
        23: {'name_en': 'Wedding Venues', 'name_fr': 'Salles de mariage', 'description_en': 'Spaces dedicated to wedding ceremonies and receptions', 'description_fr': 'Espaces dédiés aux cérémonies et réceptions de mariage'},
        24: {'name_en': 'Reception Halls', 'name_fr': 'Salles de réception', 'description_en': 'Multi-purpose halls for birthdays, baptisms, communions', 'description_fr': 'Salles polyvalentes pour anniversaires, baptêmes, communions'},
        25: {'name_en': 'Event Spaces', 'name_fr': 'Espaces événementiels', 'description_en': 'Venues for corporate events, seminars, conferences', 'description_fr': 'Lieux pour événements corporate, séminaires, conférences'},
        26: {'name_en': 'Gardens & Terraces', 'name_fr': 'Jardins & Terrasses', 'description_en': 'Outdoor spaces with gardens for outdoor events', 'description_fr': 'Espaces extérieurs avec jardins pour événements en plein air'},
        27: {'name_en': 'Villas & Private Residences', 'name_fr': 'Villas & Résidences privées', 'description_en': 'Complete villa rental for intimate events', 'description_fr': 'Location de villas complètes pour événements intimes'},
        28: {'name_en': 'Community Halls', 'name_fr': 'Salles communautaires', 'description_en': 'Community centers, parish halls', 'description_fr': 'Centres communautaires, salles paroissiales'},
        29: {'name_en': 'Themed Spaces', 'name_fr': 'Espaces thématiques', 'description_en': 'Places with specific decoration (beach club, rooftop, etc.)', 'description_fr': 'Lieux avec décoration spécifique (beach club, rooftop, etc.)'},
        30: {'name_en': 'Drivers & VTC', 'name_fr': 'Chauffeurs & VTC', 'description_en': 'Uber, Bolt, private drivers', 'description_fr': 'Uber, Bolt, chauffeurs privés'},
        31: {'name_en': 'Moving & Delivery', 'name_fr': 'Déménagement & Livraison', 'description_en': 'Furniture transport, goods, home delivery', 'description_fr': 'Transport de meubles, marchandises, courses à domicile'},
        32: {'name_en': 'Mechanics & Auto Repair', 'name_fr': 'Mécaniciens & Réparateurs automobiles', 'description_en': 'Repair, breakdown service, maintenance', 'description_fr': 'Réparation, dépannage, maintenance'},
        33: {'name_en': 'Car Wash', 'name_fr': 'Lavage Auto', 'description_en': 'Home services or station services', 'description_fr': 'Services à domicile ou en station'},
        34: {'name_en': 'Nurses & Home Care', 'name_fr': 'Infirmiers & Soins à domicile', 'description_en': 'Elderly care, infusions', 'description_fr': 'Soins aux personnes âgées, perfusions'},
        35: {'name_en': 'Psychologists & Therapists', 'name_fr': 'Psychologues & Thérapeutes', 'description_en': 'Private consultations, stress management', 'description_fr': 'Consultations privées, gestion du stress'},
        36: {'name_en': 'Speech Therapists & Physiotherapists', 'name_fr': 'Orthophonistes & Kinésithérapeutes', 'description_en': 'Rehabilitation, speech therapy', 'description_fr': 'Rééducation, thérapie du langage'},
        37: {'name_en': 'Lawyers & Legal Advisors', 'name_fr': 'Avocats & Conseillers juridiques', 'description_en': 'Business law, real estate, divorce', 'description_fr': 'Droits des affaires, immobilier, divorce'},
        38: {'name_en': 'Accountants & Tax Specialists', 'name_fr': 'Comptables & Fiscalistes', 'description_en': 'Tax management, business accounting', 'description_fr': 'Gestion d\'impôts, comptabilité d\'entreprise'},
        39: {'name_en': 'Consultants & Career Coaches', 'name_fr': 'Consultants & Coachs de carrière', 'description_en': 'Business consulting, personal development', 'description_fr': 'Business consulting, développement personnel'},
        40: {'name_en': 'Translation & Interpretation', 'name_fr': 'Traduction & Interprétation', 'description_en': 'Portuguese-French-English, etc.', 'description_fr': 'Portugais-français-anglais, etc.'},
        41: {'name_en': 'Training & Private Lessons', 'name_fr': 'Formations & Cours particuliers', 'description_en': 'Languages, computer science, music, tutoring', 'description_fr': 'Langues, informatique, musique, soutien scolaire'},
        42: {'name_en': 'Web & Mobile Development', 'name_fr': 'Développement Web & Mobile', 'description_en': 'Website creation, applications', 'description_fr': 'Création de sites, applications'},
        43: {'name_en': 'Graphics & Design', 'name_fr': 'Graphisme & Design', 'description_en': 'Logos, flyers, UX/UI design', 'description_fr': 'Logos, flyers, design UX/UI'},
        44: {'name_en': 'Digital Marketing & Social Media', 'name_fr': 'Marketing Digital & Réseaux sociaux', 'description_en': 'Community management, online advertising', 'description_fr': 'Community management, publicité en ligne'},
        45: {'name_en': 'IT Support & Repair', 'name_fr': 'Support Informatique & Réparation', 'description_en': 'PC troubleshooting, software installation', 'description_fr': 'Dépannage PC, installation de logiciels'},
        46: {'name_en': 'Veterinarians & Pet Care', 'name_fr': 'Vétérinaires & Soins pour animaux', 'description_en': 'Vaccines, consultations', 'description_fr': 'Vaccins, consultations'},
        47: {'name_en': 'Pet Grooming', 'name_fr': 'Toilettage pour animaux', 'description_en': 'Baths, cuts, specialized care', 'description_fr': 'Bains, coupes, soins spécialisés'},
        48: {'name_en': 'Trainers & Pet Sitting', 'name_fr': 'Dresseurs & Garde d\'animaux', 'description_en': 'Dog-sitting, training', 'description_fr': 'Dog-sitting, dressage'},
        49: {'name_en': 'Security Guards & Surveillance', 'name_fr': 'Agents de sécurité & Gardiennage', 'description_en': 'Private security, surveillance', 'description_fr': 'Sécurité privée, surveillance'},
        50: {'name_en': 'Concierge & Home Services', 'name_fr': 'Conciergerie & Services à domicile', 'description_en': 'Shopping, property management', 'description_fr': 'Courses, gestion de propriétés'},
        51: {'name_en': 'Manufacturing & Custom Sales', 'name_fr': 'Fabrication & Vente sur mesure', 'description_en': 'Seamstresses, tailors, cobblers', 'description_fr': 'Couturiers, tailleurs, cordonniers'}
    }
    
    # Mettre à jour les catégories
    for category in Category.objects.all():
        if category.id in categories_translations:
            translation = categories_translations[category.id]
            category.name_en = translation['name_en']
            category.name_fr = translation['name_fr']
            category.description_en = translation['description_en']
            category.description_fr = translation['description_fr']
            category.save()
    
    # Mettre à jour les sous-catégories
    for subcategory in SubCategory.objects.all():
        if subcategory.id in subcategories_translations:
            translation = subcategories_translations[subcategory.id]
            subcategory.name_en = translation['name_en']
            subcategory.name_fr = translation['name_fr']
            subcategory.description_en = translation['description_en']
            subcategory.description_fr = translation['description_fr']
            subcategory.save()

def reverse_populate_translation_fields(apps, schema_editor):
    """
    Fonction inverse pour supprimer les traductions (en cas de rollback)
    """
    Category = apps.get_model('operation', 'Category')
    SubCategory = apps.get_model('operation', 'SubCategory')
    
    # Vider les champs de traduction
    Category.objects.all().update(name_en=None, name_fr=None, description_en=None, description_fr=None)
    SubCategory.objects.all().update(name_en=None, name_fr=None, description_en=None, description_fr=None)

class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_remove_category_created_at_and_more'),
    ]   

    operations = [
        migrations.RunPython(
            populate_translation_fields,
            reverse_populate_translation_fields
        ),
    ]
