# Generated by Django 5.2 on 2025-07-12 08:34

from django.db import migrations, models  
from django.utils import timezone
from datetime import datetime, timedelta
from django.contrib.auth.hashers import make_password
import random

def create_test_data(apps, schema_editor):
    """
    Créer des données de test : utilisateurs, projets, services et avis
    """
    # Récupérer les modèles
    User = apps.get_model('operation', 'User')
    Provider = apps.get_model('operation', 'Provider')
    Category = apps.get_model('operation', 'Category')
    SubCategory = apps.get_model('operation', 'SubCategory')
    ClientProject = apps.get_model('operation', 'ClientProject')
    ProviderService = apps.get_model('operation', 'ProviderService')
    Review = apps.get_model('operation', 'Review')
    
    # Créer les utilisateurs de test s'ils n'existent pas
    client_user, created = User.objects.get_or_create(
        email='newclient@gmail.com',
        defaults={
            'username': 'client_test',
            'first_name': 'João',
            'last_name': 'Silva',
            'password': make_password('#!@dm1n!#'),
            'role': 'client',
            'phone_number': '+244 923 456 789',
            'location': 'Luanda, Angola',
            'bio': 'Cliente regular da plataforma Teyago Services',
            'is_verified': True,
            'is_active': True,
        }
    )
    
    provider_user, created = User.objects.get_or_create(
        email='newprestataire@gmail.com',
        defaults={
            'username': 'provider_test',
            'first_name': 'Maria',
            'last_name': 'Santos',
            'password': make_password('#!@dm1n!#'),
            'role': 'provider',
            'phone_number': '+244 912 345 678',
            'location': 'Luanda, Angola',
            'bio': 'Prestadora de serviços profissional com 10 anos de experiência',
            'is_verified': True,
            'is_active': True,
        }
    )
    
    # Créer des utilisateurs supplémentaires
    additional_users = []
    for i in range(3):
        user, created = User.objects.get_or_create(
            email=f'user{i+1}@example.com',
            defaults={
                'username': f'user_{i+1}',
                'first_name': ['Carlos', 'Ana', 'Pedro'][i],
                'last_name': ['Mendes', 'Costa', 'Fernandes'][i],
                'password': make_password('#!@dm1n!#'),
                'role': random.choice(['client', 'provider']),
                'phone_number': f'+244 9{random.randint(10,99)} {random.randint(100,999)} {random.randint(100,999)}',
                'location': random.choice(['Luanda, Angola', 'Benguela, Angola', 'Huambo, Angola']),
                'is_verified': True,
                'is_active': True,
            }
        )
        additional_users.append(user)
    
    # Créer le profil prestataire
    provider, created = Provider.objects.get_or_create(
        user=provider_user,
        defaults={
            'company_name': 'Santos Serviços Profissionais',
            'is_verified': True,
            'is_featured': False,
            'avg_rating': 4.8,
            'trust_score': 4.5,
            'address': 'Luanda, Angola',
        }
    )
    
    # Récupérer quelques catégories et sous-catégories
    try:
        casa_construcao = Category.objects.get(id=1)  # Casa & Construção
        bem_estar = Category.objects.get(id=2)        # Bem-estar & Beleza
        eventos = Category.objects.get(id=3)          # Eventos & Artísticos
        
        # Sous-catégories
        construcao_sub = SubCategory.objects.get(id=1)    # Construção & Renovação
        pintura_sub = SubCategory.objects.get(id=5)       # Pintura & Decoração
        limpeza_sub = SubCategory.objects.get(id=8)       # Limpeza & Manutenção
        fotografia_sub = SubCategory.objects.get(id=17)   # Fotografia & Videografia
        coiffure_sub = SubCategory.objects.get(id=12)     # Cabeleireiro & Barbeiro
    except Exception as e:
        print(f"Erreur: Les catégories n'existent pas encore: {e}")
        return
    
    # Créer 5 projets avec SEULEMENT les champs existants du modèle ClientProject
    projets_data = [
        {
            'title': 'Renovação Completa de Apartamento',
            'description': 'Preciso renovar completamente meu apartamento de 3 quartos em Luanda. Inclui pintura, troca de pisos, renovação da cozinha e banheiros. Prazo de 2 meses.',
            'category': casa_construcao,
            'subcategory': construcao_sub,
            'budget_range': '15000_plus',  # Utilise les choix valides
            'min_budget': 500000,
            'max_budget': 1000000,
            'location': 'Luanda, Maianga',
            'urgency': 'medium',
            'deadline': timezone.now() + timedelta(days=60),
        },
        {
            'title': 'Pintura Externa de Casa',
            'description': 'Casa de 200m² precisa de pintura externa completa. Inclui preparação das paredes, massa corrida e duas demãos de tinta.',
            'category': casa_construcao,
            'subcategory': pintura_sub,
            'budget_range': '5000_15000',
            'min_budget': 100000,
            'max_budget': 200000,
            'location': 'Luanda, Talatona',
            'urgency': 'low',
            'deadline': timezone.now() + timedelta(days=30),
        },
        {
            'title': 'Limpeza Pós-Construção',
            'description': 'Preciso de limpeza profissional após reforma. Remoção de entulhos, limpeza de janelas, pisos e paredes.',
            'category': casa_construcao,
            'subcategory': limpeza_sub,
            'budget_range': '1000_5000',
            'min_budget': 50000,
            'max_budget': 100000,
            'location': 'Luanda, Ingombota',
            'urgency': 'high',
            'deadline': timezone.now() + timedelta(days=7),
        },
        {
            'title': 'Fotografia de Casamento',
            'description': 'Procuro fotógrafo profissional para casamento em dezembro. Cerimônia e festa, aproximadamente 8 horas de cobertura.',
            'category': eventos,
            'subcategory': fotografia_sub,
            'budget_range': '15000_plus',
            'min_budget': 200000,
            'max_budget': 400000,
            'location': 'Luanda, Ilha do Cabo',
            'urgency': 'medium',
            'deadline': timezone.now() + timedelta(days=90),
        },
        {
            'title': 'Corte de Cabelo Domiciliar',
            'description': 'Preciso de cabeleireiro que atenda em domicílio para minha família (4 pessoas). Serviço mensal.',
            'category': bem_estar,
            'subcategory': coiffure_sub,
            'budget_range': '500_1000',
            'min_budget': 20000,
            'max_budget': 40000,
            'location': 'Luanda, Miramar',
            'urgency': 'low',
            'deadline': timezone.now() + timedelta(days=14),
        }
    ]
    
    created_projects = []
    for i, projet_data in enumerate(projets_data):
        projet, created = ClientProject.objects.get_or_create(
            title=projet_data['title'],
            defaults={
                'client': client_user,
                'description': projet_data['description'],
                'category': projet_data['category'],
                'subcategory': projet_data['subcategory'],
                'budget_range': projet_data['budget_range'],
                'min_budget': projet_data['min_budget'],
                'max_budget': projet_data['max_budget'],
                'location': projet_data['location'],
                'remote_possible': False,
                'deadline': projet_data['deadline'],
                'urgency': projet_data['urgency'],
                'status': random.choice(['open', 'open', 'in_progress']),
                'contact_via_platform': True,
                'show_email': False,
                'show_phone': True,
                'views_count': random.randint(15, 50),  # Champ qui existe vraiment
                # Supprimé : offers_count, required_skills (n'existent pas dans le modèle)
            }
        )
        created_projects.append(projet)
    
    # Créer 5 services
    services_data = [
        {
            'title': 'Reformas e Renovações Residenciais',
            'description': 'Serviços completos de reforma e renovação para residências. Desde pequenos reparos até renovações completas. Equipe qualificada e materiais de qualidade.',
            'subcategory': construcao_sub,
            'price_type': 'quote',
            'price': 50000,
        },
        {
            'title': 'Pintura Residencial e Comercial',
            'description': 'Pintura interna e externa para residências e comércios. Preparação de superfícies, massa corrida, tinta de qualidade. Garantia de 2 anos.',
            'subcategory': pintura_sub,
            'price_type': 'hourly',
            'price': 2500,
        },
        {
            'title': 'Limpeza Residencial e Comercial',
            'description': 'Serviços de limpeza para residências, escritórios e pós-obra. Equipe treinada, produtos ecológicos, flexibilidade de horários.',
            'subcategory': limpeza_sub,
            'price_type': 'hourly',
            'price': 3000,
        },
        {
            'title': 'Fotografia Profissional de Eventos',
            'description': 'Cobertura fotográfica para casamentos, aniversários, eventos corporativos. Edição profissional incluída, entrega em 15 dias.',
            'subcategory': fotografia_sub,
            'price_type': 'fixed',
            'price': 250000,
        },
        {
            'title': 'Serviços de Cabeleireiro Domiciliar',
            'description': 'Cortes, penteados e tratamentos capilares no conforto da sua casa. Atendimento para toda família, produtos de qualidade.',
            'subcategory': coiffure_sub,
            'price_type': 'fixed',
            'price': 8000,
        }
    ]
    
    created_services = []
    for i, service_data in enumerate(services_data):
        service, created = ProviderService.objects.get_or_create(
            title=service_data['title'],
            provider=provider,
            defaults={
                'description': service_data['description'],
                'subcategory': service_data['subcategory'],
                'price_type': service_data['price_type'],
                'price': service_data['price'],
                'is_available': True,
            }
        )
        created_services.append(service)
    
    # Créer des avis réalistes
    avis_data = [
        {
            'service': created_services[0],  # Reformas
            'client': client_user,
            'rating': 5,
            'comment': 'Excelente trabalho! A equipe foi pontual, profissional e o resultado ficou melhor do que esperava. Recomendo muito!',
        },
        {
            'service': created_services[0],  # Reformas
            'client': additional_users[0],
            'rating': 4,
            'comment': 'Bom serviço, cumpriram o prazo. Apenas alguns pequenos detalhes que foram corrigidos depois.',
        },
        {
            'service': created_services[1],  # Pintura
            'client': client_user,
            'rating': 5,
            'comment': 'Pintura impecável! Muito cuidadosos com móveis e objetos. Limparam tudo depois. Nota 10!',
        },
        {
            'service': created_services[1],  # Pintura
            'client': additional_users[1],
            'rating': 5,
            'comment': 'Trabalho de qualidade, usaram tinta boa e o acabamento ficou perfeito. Preço justo.',
        },
        {
            'service': created_services[2],  # Limpeza
            'client': additional_users[0],
            'rating': 4,
            'comment': 'Serviço de limpeza muito bom. Deixaram tudo brilhando. Pontuais e educados.',
        },
        {
            'service': created_services[3],  # Fotografia
            'client': client_user,
            'rating': 5,
            'comment': 'Fotógrafo incrível! Capturou todos os momentos especiais do nosso casamento. Fotos lindas!',
        },
        {
            'service': created_services[3],  # Fotografia
            'client': additional_users[2],
            'rating': 4,
            'comment': 'Muito profissional, entregou no prazo. Algumas fotos ficaram excepcionais.',
        },
        {
            'service': created_services[4],  # Cabeleireiro
            'client': additional_users[1],
            'rating': 5,
            'comment': 'Adorei o atendimento! Muito prático ter o cabeleireiro em casa. Corte perfeito!',
        },
        {
            'service': created_services[0],  # Reformas - mais um
            'client': additional_users[2],
            'rating': 5,
            'comment': 'Transformaram minha casa! Trabalho impecável, equipe educada e preço honesto.',
        },
        {
            'service': created_services[1],  # Pintura - mais um
            'client': additional_users[0],
            'rating': 4,
            'comment': 'Bom trabalho de pintura. Pontuais e organizados. Recomendo!',
        }
    ]
    
    # Créer les avis
    for avis in avis_data:
        Review.objects.get_or_create(
            service=avis['service'],
            client=avis['client'],
            defaults={
                'provider': provider,
                'quality_rating': avis['rating'],
                'punctuality_rating': avis['rating'],
                'value_rating': avis['rating'],
                'overall_rating': avis['rating'],  # AJOUT DU CHAMP MANQUANT
                'comment': avis['comment'],
                'is_verified': True,
            }
        )
    
    # Mettre à jour les statistiques du prestataire
    total_reviews = Review.objects.filter(provider=provider).count()
    if total_reviews > 0:
        from django.db.models import Avg
        avg_quality = Review.objects.filter(provider=provider).aggregate(
            avg_rating=Avg('quality_rating')
        )['avg_rating']
        
        if avg_quality:
            provider.avg_rating = round(avg_quality, 1)
            provider.save()
    
    print(f"✅ Données de test créées avec succès:")
    print(f"   - {len(created_projects)} projets")
    print(f"   - {len(created_services)} services")
    print(f"   - {len(avis_data)} avis")
    print(f"   - Utilisateur client: newclient@gmail.com")
    print(f"   - Utilisateur prestataire: newprestataire@gmail.com")
    print(f"   - Mot de passe: #!@dm1n!#")

def remove_test_data(apps, schema_editor):
    """
    Supprimer les données de test
    """
    User = apps.get_model('operation', 'User')
    Provider = apps.get_model('operation', 'Provider')
    ClientProject = apps.get_model('operation', 'ClientProject')
    ProviderService = apps.get_model('operation', 'ProviderService')
    Review = apps.get_model('operation', 'Review')
    
    # Supprimer les données de test
    Review.objects.filter(client__email__in=['newclient@gmail.com', 'user1@example.com', 'user2@example.com', 'user3@example.com']).delete()
    ProviderService.objects.filter(provider__user__email='newprestataire@gmail.com').delete()
    ClientProject.objects.filter(client__email='newclient@gmail.com').delete()
    Provider.objects.filter(user__email='newprestataire@gmail.com').delete()
    User.objects.filter(email__in=[
        'newclient@gmail.com', 
        'newprestataire@gmail.com',
        'user1@example.com',
        'user2@example.com', 
        'user3@example.com'
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_auto_20250712_0835'),
    ]

    operations = [
        migrations.RunPython(
            create_test_data,
            remove_test_data
        ),
    ]