# Generated by Django 5.2 on 2025-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_auto_20250712_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
