# Generated by Django 5.2 on 2025-07-19 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Notes internes pour l'administration", verbose_name='Notes administratives'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution'),
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('project_status_change', 'Changement statut projet'), ('project_close', 'Fermeture projet'), ('project_reopen', 'Réouverture projet'), ('dispute_status_change', 'Changement statut litige'), ('dispute_resolve', 'Résolution litige'), ('user_suspend', 'Suspension utilisateur'), ('provider_verify', 'Vérification prestataire'), ('bulk_action', 'Action groupée')], max_length=50, verbose_name="Type d'action")),
                ('target_model', models.CharField(max_length=50, verbose_name='Modèle cible')),
                ('target_id', models.PositiveIntegerField(verbose_name="ID de l'objet")),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Action Administrateur',
                'verbose_name_plural': 'Actions Administrateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('setting_type', models.CharField(choices=[('string', 'Texte'), ('integer', 'Nombre entier'), ('float', 'Nombre décimal'), ('boolean', 'Booléen'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Type de paramètre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Visible publiquement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètre Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
    ]
