# Generated by Django 5.2 on 2025-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Nouveau message'), ('review', 'Nouvel avis'), ('favorite', 'Nouveau favoris'), ('dispute', 'Litige'), ('system', 'Notification système'), ('quote_request', 'Demande de devis'), ('quote_accepted', 'Devis accepté'), ('quote_rejected', 'Devis rejeté'), ('quote_completed', 'Devis terminé'), ('new_offer', 'Nouvelle offre'), ('offer_accepted', 'Offre acceptée'), ('offer_rejected', 'Offre rejetée')], max_length=20, null=True),
        ),
    ]
