# Generated by Django 5.2 on 2025-07-30 11:46

from django.db import migrations
from operation.models import User
from django.contrib.auth.hashers import make_password
from django.utils import timezone


def create_default_admin(apps, schema_editor):
    """
    Créer l'administrateur par défaut admin@gmail.com
    """
    # Informations admin par défaut
    admin_email = 'admin1@gmail.com'
    admin_username = 'admin'
    
    # Vérifier si l'admin existe déjà
    if User.objects.filter(email=admin_email).exists():
        print(f"✅ L'administrateur {admin_email} existe déjà - migration ignorée")
        return
    
    # Vérifier si le username existe et le modifier si nécessaire
    original_username = admin_username
    counter = 1
    while User.objects.filter(username=admin_username).exists():
        admin_username = f"{original_username}{counter}"
        counter += 1
    
    # Générer un mot de passe sécurisé
    password = "#!@dm1n!#"
    
    # Créer l'utilisateur administrateur
    admin_user = User.objects.create(
        username=admin_username,
        email=admin_email,
        password=make_password(password),  # Hash le mot de passe
        first_name='Administrateur',
        last_name='Principal',
        is_staff=True,
        is_superuser=True,
        is_active=True,
        date_joined=timezone.now()
    )
    
    # Créer un fichier avec les informations de connexion
    credentials_file = '/tmp/admin_credentials.txt'
    try:
        with open(credentials_file, 'w') as f:
            f.write("="*50 + "\n")
            f.write("🔐 INFORMATIONS ADMINISTRATEUR CRÉÉ\n")
            f.write("="*50 + "\n")
            f.write(f"Email: {admin_email}\n")
            f.write(f"Username: {admin_username}\n")
            f.write(f"Password: {password}\n")
            f.write(f"User ID: {admin_user.id}\n")
            f.write(f"Created: {admin_user.date_joined}\n")
            f.write(f"URL Admin: https://teyago.com/login\n")
            f.write("="*50 + "\n")
            f.write("⚠️  IMPORTANT: Sauvegardez ces informations et supprimez ce fichier après utilisation!\n")
            f.write("⚠️  Commande de suppression: rm /tmp/admin_credentials.txt\n")
            f.write("="*50 + "\n")
    except Exception as e:
        print(f"⚠️  Impossible de créer le fichier credentials: {e}")
    
    # Afficher les informations dans la console
    print("\n" + "="*60)
    print("🎉 ADMINISTRATEUR CRÉÉ AVEC SUCCÈS!")
    print("="*60)
    print(f"📧 Email: {admin_email}")
    print(f"👤 Username: {admin_username}")
    print(f"🔑 Password: {password}")
    print(f"🆔 User ID: {admin_user.id}")
    print(f"🔗 URL Admin: https://teyago.com/login")
    print("="*60)
    print(f"💾 Credentials sauvegardés dans: {credentials_file}")
    print("⚠️  SUPPRIMEZ ce fichier après utilisation!")
    print("="*60)

def remove_default_admin(apps, schema_editor):
    """
    Fonction de rollback - supprime l'admin créé
    """
    admin_email = 'admin@gmail.com'
    
    try:
        admin_user = User.objects.get(email=admin_email)
        admin_user.delete()
        print(f"🗑️  Administrateur {admin_email} supprimé lors du rollback")
    except User.DoesNotExist:
        print(f"⚠️  Administrateur {admin_email} non trouvé pour suppression")



class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_alter_notification_options_and_more'),
    ]

    operations = [
        # migrations.RunPython(
        #     create_default_admin,
        #     remove_default_admin,
        #     elidable=True,
        # ),
    ]
