# Generated by Django 5.2 on 2025-07-31 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_auto_20250730_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.CharField(choices=[('project_status_change', 'Changement statut projet'), ('project_close', 'Fermeture projet'), ('project_reopen', 'Réouverture projet'), ('dispute_status_change', 'Changement statut litige'), ('dispute_resolve', 'Résolution litige'), ('user_suspend', 'Suspension utilisateur'), ('provider_verify', 'Vérification prestataire'), ('bulk_action', 'Action groupée'), ('provider_verification_approve', 'Approbation vérification prestataire'), ('provider_verification_reject', 'Rejet vérification prestataire'), ('phone_verification_reset', 'Reset vérification téléphone'), ('verification_bulk_action', 'Action groupée vérifications')], max_length=50, verbose_name="Type d'action"),
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Code de vérification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('expired', 'Expiré'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Tentatives maximales')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('last_code_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Dernier code envoyé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vérification Téléphone',
                'verbose_name_plural': 'Vérifications Téléphone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_business', models.BooleanField(default=False, verbose_name='Est une entreprise')),
                ('document_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport')], default='id_card', max_length=20, verbose_name='Type de document')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('business_nif', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, verbose_name="NIF de l'entreprise")),
                ('business_registration_number', models.CharField(blank=True, help_text='Numéro RCCM ou équivalent', max_length=100, verbose_name="Numéro d'enregistrement")),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='verifications/id_cards/front/', verbose_name="Carte d'identité (recto)")),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='verifications/id_cards/back/', verbose_name="Carte d'identité (verso)")),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='verifications/passports/', verbose_name='Photo du passeport')),
                ('business_registration_doc', models.FileField(blank=True, null=True, upload_to='verifications/business_docs/', verbose_name="Document d'enregistrement d'entreprise")),
                ('verification_status', models.CharField(choices=[('not_started', 'Non commencé'), ('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='not_started', max_length=20, verbose_name='Statut de vérification')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administratives')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='operation.provider', verbose_name='Prestataire')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Vérification Prestataire',
                'verbose_name_plural': 'Vérifications Prestataires',
                'ordering': ['-created_at'],
            },
        ),
    ]
