# Generated by Django 5.2.8 on 2025-11-14 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_alter_adminaction_action_type_phoneverification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputeevidence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Preuve de litige', 'verbose_name_plural': 'Preuves de litiges'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'service')},
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='evidence_type',
            field=models.CharField(choices=[('document', 'Document avec fichier'), ('comment', 'Commentaire textuel')], default='comment', help_text='Type de preuve : document avec fichier ou simple commentaire', max_length=20),
        ),
        migrations.AddField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Le service ajouté en favori', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='operation.providerservice'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Données supplémentaires pour navigation précise', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='disputeevidence',
            name='file',
            field=models.FileField(blank=True, help_text='Fichier optionnel pour la preuve (image ou document)', null=True, upload_to='dispute_evidence/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Nouveau message'), ('review', 'Nouvel avis'), ('favorite', 'Nouveau favoris'), ('dispute', 'Litige'), ('system', 'Notification système'), ('quote_request', 'Demande de devis'), ('quote_accepted', 'Devis accepté'), ('quote_rejected', 'Devis rejeté'), ('quote_completed', 'Devis terminé'), ('new_offer', 'Nouvelle offre'), ('offer_accepted', 'Offre acceptée'), ('offer_rejected', 'Offre rejetée'), ('profile_rejected', 'Vérification rejetée'), ('profile_verified', 'Profil vérifié'), ('phone_verified', 'Téléphone vérifié'), ('new_message', 'Nouveau message'), ('project_created', 'Projet créé'), ('project_completed', 'Projet terminé'), ('project_update', 'Mise à jour projet')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('user_registration', 'Nouvel utilisateur'), ('document_submission', 'Documents soumis'), ('project_created', 'Nouveau projet'), ('offer_submitted', 'Nouvelle offre'), ('dispute_created', 'Nouveau litige'), ('dispute_evidence', 'Nouvelle preuve'), ('verification_request', 'Demande de vérification'), ('payment_received', 'Paiement reçu'), ('system_alert', 'Alerte système')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevée'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Admin',
                'verbose_name_plural': 'Notifications Admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport')], default='id_card', max_length=20, verbose_name='Type de document')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='verifications/clients/id_cards/front/', verbose_name="Carte d'identité (recto)")),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='verifications/clients/id_cards/back/', verbose_name="Carte d'identité (verso)")),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='verifications/clients/passports/', verbose_name='Photo du passeport')),
                ('verification_status', models.CharField(choices=[('not_started', 'Non commencé'), ('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='not_started', max_length=20, verbose_name='Statut de vérification')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administratives')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_verification', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clients', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Vérification Client',
                'verbose_name_plural': 'Vérifications Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token FCM',
                'verbose_name_plural': 'Tokens FCM',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('delivered', 'Livrée'), ('failed', 'Échouée'), ('clicked', 'Cliquée')], default='pending', max_length=20)),
                ('firebase_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.fcmtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de notification',
                'verbose_name_plural': 'Historiques de notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_enabled', models.BooleanField(default=True)),
                ('offers_enabled', models.BooleanField(default=True)),
                ('projects_enabled', models.BooleanField(default=True)),
                ('reviews_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Début des heures silencieuses', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fin des heures silencieuses', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='provider',
        ),
        migrations.CreateModel(
            name='FavoriteProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='operation.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_providers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='favorite_pr_user_id_cdfb40_idx'), models.Index(fields=['-created_at'], name='favorite_pr_created_29bb87_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'is_active'], name='operation_f_user_id_6e8e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['token'], name='operation_f_token_019e62_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', 'status'], name='operation_n_user_id_66dcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['notification_type'], name='operation_n_notific_05dab3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['created_at'], name='operation_n_created_ac2af7_idx'),
        ),
    ]
